### ISSUE TITLE
sanitise / force wrap message input in quotes

### ISSUE THREAD

**Issue by damsleth** [Puzzlepart/sexy-commits#2]
message input does not get sanitised or wrapped in a string, meaning the program bombs if i do e.g
```sexy-commits all chore spelingError => spellingError``` 

don't know if it's possible to force-wrap/stringify a `process.arg` 🤔

**Comment by olemp** [comment]
> message input does not get sanitised or wrapped in a string, meaning the program bombs if i do e.g
> `sexy-commits all chore spelingError => spellingError`
> 
> don't know if it's possible to force-wrap/stringify a `process.arg` 🤔

Hmmm you probably have to quote it, we just get an array of args when the args are going through the npm script!

**Comment by olemp** [comment]
See if https://github.com/Puzzlepart/sexy-commits/commit/610132b585cce1ccfe4d72b467e3e75453854482 does it for yo.

![image](https://user-images.githubusercontent.com/7606007/113025066-c82df680-9187-11eb-89a4-7cc19a80acc6.png)

The rest of the elements are set to `message_` then it's joined by a space to `message`.
